import React, { useMemo } from 'react'
import { Link } from 'react-router-dom'
import { CYCLE_SVG } from '../data/cycleMarks.js'
import '../styles/cycle-ring.css'

/* ============================================================================
   CycleRing · the delivery cycle as a ring (23 Sep 2026).

   Bazil, with a reference of a six-node wheel around an isometric render: "I like this style on this, can you improve
   the design more." This is that composition, built from what the site already holds: the six stages of the delivery
   cycle and their 3D stills.

   HOW IT IS BUILT
     · One hairline circle carries the whole cycle, and the six nodes sit on it at 60 degree steps starting at the
       top, in the order they are built on site. The arc from the previous node to the active one is drawn in the
       client red, so the ring reads as progress rather than as decoration.
     · Each node is a white disc holding that stage's still, with the number and the name under it in the label face.
       The active node takes a red ring and a red label; nothing else changes colour.
     · The centre carries the active stage: its still, its name, its one line, and the way into its page.
     · Geometry is laid out on a fixed 1000 x 1000 viewBox and scaled to its container, so the composition never
       drifts as the column changes width. Below 860 px the ring is dropped for a straight list, which is what a
       phone can actually read.
   ============================================================================ */

const R = 355            /* ring radius on the 1000 grid */
const CX = 500, CY = 500
const NODE = 86          /* node disc diameter */

const pt = (i, n, r = R) => {
  const a = (i / n) * Math.PI * 2 - Math.PI / 2
  return [CX + Math.cos(a) * r, CY + Math.sin(a) * r]
}
/* the arc is trimmed at both ends by the node's own radius, so it stops at the disc rather than running under it */
const arc = (from, to, n, r = R, trim = 7.2) => {
  const a0 = (from / n) * 360 - 90 + trim
  const a1 = (to / n) * 360 - 90 - trim
  const P = d => [CX + Math.cos(d * Math.PI / 180) * r, CY + Math.sin(d * Math.PI / 180) * r]
  const [x1, y1] = P(a0), [x2, y2] = P(a1)
  const span = ((a1 - a0) + 360) % 360
  return `M${x1.toFixed(1)} ${y1.toFixed(1)}A${r} ${r} 0 ${span > 180 ? 1 : 0} 1 ${x2.toFixed(1)} ${y2.toFixed(1)}`
}

/* 23 Sep (Bazil, on the reference wheel: "I like the 3D look of this kind of design, but why is it not detailed
   enough"): the discs were carrying photographs. They carry the ISOMETRIC CYCLE MARKS now, which is what the
   reference does and what this build already owns: the Hard Anodise set, one lamp, one palette, a red part on the
   piece that acts (data/cycleMarks.js, generated by scripts_marks_build.mjs --cycle). The centre keeps the
   photograph, so the ring reads as drawing and the middle as the real thing. */
const MARK_KEY = ['des', 'prc', 'con', 'com', 'mnt', 'hok']

/* 24 Sep (Bazil: "what about the process of 1 to 6, and a special one that goes back to repeat the process; last time
   we had this kind of diagram"): the ring reads as a process now. A chevron on every hand-off points the way round,
   the hand-offs already made are red, and the return from 6 to 1 is its own path: dashed red, an arrowhead landing
   on Design, and its name beside it. The serpentine carried the same return; the ring lost it on 23 Sep. */
const DEG = d => d * Math.PI / 180
const onRing = (deg, r = R) => [CX + Math.cos(DEG(deg)) * r, CY + Math.sin(DEG(deg)) * r]
/* a chevron at the middle of the hand-off from i to i+1, pointing clockwise */
const chevron = (i, n) => { const d = ((i + 0.5) / n) * 360 - 90; const [x, y] = onRing(d); return `translate(${x.toFixed(1)} ${y.toFixed(1)}) rotate(${(d + 90).toFixed(1)})` }
const RETURN_END = (0 / 6) * 360 - 90 - 7.2

export default function CycleRing ({ stages = [], active = 0, onStage, stills = [], loops = [] }) {
  const n = stages.length || 6
  const nodes = useMemo(() => stages.map((s, i) => ({ s, i, p: pt(i, n) })), [stages, n])
  const cur = stages[active] || stages[0]
  if (!cur) return null

  return (
    <div className="cring" data-reveal="">
      <div className="cring-stage">
        <svg className="cring-svg" viewBox="0 0 1000 1000" role="presentation">
          <circle cx={CX} cy={CY} r={R} className="cring-track" />
          <path d={arc(n - 1, 0, n)} className="cring-return" />
          <g transform={`translate(${onRing(RETURN_END)[0].toFixed(1)} ${onRing(RETURN_END)[1].toFixed(1)}) rotate(${(RETURN_END + 90).toFixed(1)})`}><path d="M0 0L-16 -9L-16 9Z" className="cring-return-head" /></g>
          <path d={arc((active - 1 + n) % n, active, n)} className="cring-arc" />
          {Array.from({ length: n - 1 }, (_, i) => (
            <g key={i} transform={chevron(i, n)}><path d="M-9 -9L0 0L-9 9" className={'cring-chev' + (i < active ? ' on' : '')} /></g>
          ))}
          {nodes.map(({ p, i }) => (
            <circle key={i} cx={p[0]} cy={p[1]} r={NODE / 2 + 9} className={'cring-halo' + (i === active ? ' on' : '')} />
          ))}
        </svg>

        {nodes.map(({ s, p, i }) => (
          <button
            key={s.id}
            type="button"
            className={'cring-node' + (i === active ? ' on' : '')}
            data-i={i}
            style={{ left: (p[0] / 10) + '%', top: (p[1] / 10) + '%' }}
            onPointerEnter={() => onStage && onStage(i)}
            onFocus={() => onStage && onStage(i)}
            onClick={() => onStage && onStage(i)}
            aria-pressed={i === active}
          >
            <span className="cring-disc" dangerouslySetInnerHTML={{ __html: CYCLE_SVG[MARK_KEY[i]] || '' }} />
            <span className="cring-lb"><i>{s.no}</i>{s.short}</span>
          </button>
        ))}

        {/* the return's name, outside the ring beside its arc */}
        <span className="cring-ret-l" style={{ left: (onRing(240, R + 118)[0] / 10) + '%', top: (onRing(240, R + 118)[1] / 10) + '%' }}>
          <i aria-hidden="true">&#8634;</i>6 feeds the next 1<small>Hookup feeds the next design</small>
        </span>

        <div className="cring-core" aria-live="polite">
          <div className="cring-core-art">
            {loops[active]
              ? <video src={loops[active]} poster={stills[active]} muted loop playsInline autoPlay />
              : (stills[active] ? <img src={stills[active]} alt="" decoding="async" /> : null)}
          </div>
          <p className="cring-core-k">{cur.tag}</p>
          <h3 className="cring-core-h">{cur.name}</h3>
          <p className="cring-core-d">{cur.kick}</p>
          <Link className="cring-core-go" to={cur.route}>See {cur.short}<i aria-hidden="true">&#8594;</i></Link>
        </div>
      </div>

      {/* the phone reading of the same thing: the six in order, no ring */}
      <ol className="cring-list">
        {stages.map((s, i) => (
          <li key={s.id} className={i === active ? 'on' : undefined}>
            <Link to={s.route}>
              <span className="cring-li-n">{s.no}</span>
              <span className="cring-li-t">{s.short}</span>
              <span className="cring-li-d">{s.kick}</span>
            </Link>
          </li>
        ))}
        <li className="cring-li-ret"><i aria-hidden="true">&#8634;</i>6 feeds the next 1. Hookup feeds the next design, and the cycle repeats.</li>
      </ol>
    </div>
  )
}
