import React from 'react'
import { VALUES } from '../data/values.js'
import { VALUE_ART } from '../data/valuesArt.js'

/* "Six values, held on every site." — the FOURTH attempt, and the first one with a picture in it.

   The history matters, because each attempt failed for a reason and the fix has to survive all
   three: six isometric line drawings said nothing on sight; a radial orbit was "horrible"; a
   typographic index read well but was only words. Then a ring of cards turning in perspective,
   which is what this replaces.

   10 Sep (Bazil, on the ring: "look more premium and look good please and add visual for each",
   then "maybe more isometric angle like the example i gave"). The ring failed on all three
   counts and the screenshot showed why: six billboarded cards on one cylinder overlap at any
   rotation, so titles ghosted through each other; there was no visual, only a 19px line mark in
   a corner; and a card turned to face the camera has no isometric angle left in it at all.

   This is the set as OBJECTS. Each value gets an isometric thing off an IAQ site, generated by
   the same script as the nine discipline marks, sharing their footprint, their value ladder and
   their one red face. Six cards, static, on a grid: nothing overlaps, nothing has to be dragged
   to be read, and the art is the same language as the fab drawings on the design tab.

   The objects are decorative and every one of them is captioned in text beside it, so they are
   aria-hidden and the reader loses nothing without them. */

const KEYS = ['v01', 'v02', 'v03', 'v04', 'v05', 'v06']

export default function ValuesIso() {
  return (
    <ol className="vi">
      {VALUES.map((v, i) => (
        <li className="vi-i" key={v.ix} style={{ '--d': (i % 3) * 80 + 'ms' }}>
          <span className="vi-shot" aria-hidden="true"
                dangerouslySetInnerHTML={{ __html: VALUE_ART[KEYS[i]] }} />
          <span className="vi-ix">{v.ix}</span>
          <h3>{v.title}</h3>
          <p>{v.line}</p>
        </li>
      ))}
    </ol>
  )
}
