import ContactCta from '../components/ContactCta.jsx'
import React, { useEffect } from 'react'
import { Link } from 'react-router-dom'
import Nav from '../components/Nav.jsx'
import Footer from '../components/Footer.jsx'
import FooterNav from '../components/FooterNav.jsx'
import CloseAmbient from '../components/CloseAmbient.jsx'
import IndustryGrid from '../components/IndustryGrid.jsx'
import { CYCLE_SVG } from '../data/cycleMarks.js'
import initHome from '../scenes/home.js'
import Build3D from '../components/Build3D.jsx'
/* 1 Oct: the Scroll to build 3D on the home page; false hides it (hidden in the morning, shown again the same day) */
const SHOW_BUILD3D = true
import ClosingBand from '../components/ClosingBand.jsx'
import GroupRecord from '../components/GroupRecord.jsx'
import HeroMarkets from '../components/HeroMarkets.jsx'
import '../styles/home.css'
import '../styles/mark-motion.css'

/* The six stage marks in the house "Hard Anodise" system: isometric, one lamp, one red accent
   each, generated by scripts_marks_build.mjs --cycle. They replaced the flat 24-grid line icons
   on 28 Aug (client: "make the icons 3d but simplified as it is"). */
const STEP_MARKS = ['des', 'prc', 'con', 'com', 'mnt', 'hok']
const STEP_NAMES = ['Design', 'Procure', 'Construct', 'Commission', 'Maintain', 'Hookup']
const STEP_SLUGS = ['design', 'procure', 'construct', 'commission', 'maintain', 'hookup']

export default function Home() {
  useEffect(() => {
    document.title = 'IAQ Group · Total Facility Solutions · Brand Method'
    return initHome()
  }, [])
  return (
    <>
    {/* 4 Sep BUG (found while auditing the loading screen): this overlay is z-index 99999 and
        fully opaque, and it is part of Home's tree — so navigating Home -> Markets -> Home
        remounted a FRESH, undismissed copy over the whole page. The dismiss logic is a
        module-level IIFE in scenes/home.js that runs once per page load, so nothing was left to
        clear it; it only went away seconds later, and a returning visitor sat behind a blank
        panel in the meantime. The intro belongs to the first load only. */}
    {!(typeof window !== 'undefined' && window.__iaqLoaderPlayed) && (
      <div id="loader" aria-hidden="true">
        <canvas id="loaderCv"></canvas>
        <div className="ld-ui">
          <div className="ld-logofill" id="ldLogoFill" role="img" aria-label="IAQ"></div>
          <div className="ld-row"><span className="ld-pct" id="ldPct">0%</span></div>
        </div>
      </div>
    )}
    <Nav />
    <header className="hero dark-band" id="top">
      <div className="hero-video" aria-hidden="true">
        <video className="hv" id="hv0" muted playsInline preload="auto"></video>
        <video className="hv" id="hv1" muted playsInline preload="none"></video>
      </div>
      <div className="hero-scrim" aria-hidden="true"></div>
      <canvas id="heroCanvas" aria-hidden="true"></canvas>
      <div className="hero-inner">
        <span className="eyebrow"><span data-scramble="" data-scramble-speed="22" data-scramble-stagger="26">TOTAL FACILITY SOLUTIONS · EST. 1995</span></span>
        {/* 24 Sep (Bazil: "just do what's best", after the voice pass): the brand promise from the Voice cards, 3·2,
            in place of the aspirational line. Three reveal lines; the red phrase is short enough for a phone. */}
        {/* 24 Sep (Bazil, on "The class you contract, the class you are handed": "say something better than this").
            The pun made the reader solve it before learning what IAQ does. Three plain promises now, one per business
            unit: built (EPC), proven (commissioning), kept running (EFM). */}
        {/* 25 Sep (Bazil: "a more direct title", then "no negative statements in this website"): says what IAQ does in
            three plain lines, no punctuation, the red phrase whole on its own line; the lines get room (home.css) */}
        {/* 25 Sep, later (Bazil: "use this copywriting", with the hero from the client's 24 Sep review): the line the
            client reviewed without a note on it. Three lines again, the red phrase whole on the third. */}
        {/* 25 Sep, night (Bazil: "We build / environments where / future is made, for the banner"): as he wrote it */}
        {/* 25 Sep, later (Bazil, on a cut that read "future is made": "the future is made"): the client's line in full */}
        <h1 aria-label="We build the environments where the future is made">
          <span className="hl" aria-hidden="true"><span>We build the</span></span>{' '}
          <span className="hl" aria-hidden="true"><span>environments where</span></span>{' '}
          <span className="hl" aria-hidden="true"><span>the <em>future is made</em></span></span>
        </h1>
        <p className="lede">Cleanrooms, dry rooms and the systems that hold them in spec. <span className="lede-b">Designed, built and maintained by one team for 31 years.</span></p>
        {/* one action only, per the client (24 Aug): contact, nothing competing */}
        <div className="hero-ctas">
          <Link className="cta" to="/contact">Start a project</Link>
        </div>

        {/* hero counter strip removed per the 18 Aug minutes ("remove the ...
            counter section") and Bazil's instruction of 21 Aug; it also collided
            with the market card at laptop widths. Markup lives in git history. */}

        {/* the market strip, moved into the text column on client feedback (23 Aug):
            same information as the old glass card, no box, no tiles */}
        {/* 18 Sep (Bazil: "too unprofessional, need to be more dynamic"): the uppercase label and four plain
            links became the market rail, all seven markets with their facts (components/HeroMarkets.jsx) */}
        <HeroMarkets />
      </div>

      {/* the glass market card retired 23 Aug: its content lives in the text column above */}
    </header>

    {/* 21 Sep (Bazil: "have a background colour thats great here", "better title and description",
        "a much more better world thats premium awesome and interactive with better visual for the
        numbers icon"): the section is its own component now. See components/GroupRecord.jsx. The old
        markup is in src/_backups/home-0921/Home.jsx. */}

    {/* "The film" (YouTube plant-opening card) removed on client feedback,
        19 Aug 2026 review. The markup lives in git history. */}

    {/* 28 Aug rebuild (client): the stage rail above the section is gone, the section intro moved
        into the RIGHT column above the stage copy, and the marks are the photoreal card renders
        rather than live 3D — the <canvas id="lpCv"> left the markup, which is what keeps the
        cluster renderer in scenes/home.js dormant. Six stations sit at fixed 60 degree steps and
        the red arc turns to the active one; all of the motion is CSS. */}
    {/* 17 Sep: the inline paddingBottom:0 is gone. It pinned the loop field flush to the black
        band below it, so the last station label sat 16px off the edge. The room is set on
        .lpx-band in home.css now. */}
    {/* 24 Sep: the record and the world come straight after the hero */}
    <GroupRecord />

    {/* 24 Sep, late (Bazil: "below the word there should be a circular services image diagram that we had before", then
        "this should be below the bottom section", then "where did it go?"): the ring sits under the record band */}
    <section className="sec lpx-band" id="services">
      <div className="lpx" id="lpxWrap">
        <div className="lp-intro">
          {/* 28 Aug (client): the section carries its NAME as the heading, no eyebrow above it */}
          <h2>The delivery cycle.</h2>
          <p className="lp-lede" data-reveal="">Six stages, one accountable team. Each stage hands to the next, and tools hookup feeds the next design.</p>
        </div>

        <div className="lp-field" id="lpStage">
          <div className="lp-orbit" id="lpBubbles">
            <span className="lp-trk" aria-hidden="true"></span>
            {/* three hairline runners lapping the ring once every 2s: the cycle is a loop, and
                nothing says that as fast as something travelling the whole way round */}
            <span className="lp-flow" aria-hidden="true"></span>
            {/* everything that rides the ring lives in one slowly turning layer: the arc keeps its
                own transition inside it, and each station's inner span counter-turns to stay level */}
            <div className="lp-spin">
              <span className="lp-arc" aria-hidden="true"></span>
              {STEP_NAMES.map((nm, i) => (
                <button key={nm} type="button" className={'lpn' + (i === 0 ? ' on' : '')} data-i={i}
                        style={{ '--a': (i * 60 + 30) + 'deg', '--d': (i * 0.08).toFixed(2) + 's' }}
                        aria-pressed={i === 0 ? 'true' : 'false'} aria-label={`Stage ${i + 1}: ${nm}`}>
                  <span className="lpn-in">
                    <span className="lpn-disc">
                      <span className="lpn-mk" aria-hidden="true"
                            dangerouslySetInnerHTML={{ __html: CYCLE_SVG[STEP_MARKS[i]] }} />
                    </span>
                    <span className="lpn-lb"><i>{i + 1}</i>{nm}</span>
                  </span>
                </button>
              ))}
            </div>
            {/* the six renders are stacked and crossfaded, so a stage change never reflows. Outside
                the turning layer: the centre visual holds still while the ring travels. */}
            <div className="lp-vis" aria-hidden="true">
              {STEP_SLUGS.map((s, i) => (
                <span key={s} className={'lpv' + (i === 0 ? ' on' : '')} data-i={i}
                      style={{ '--kd': (13 + i * 1.7).toFixed(1) + 's',
                               '--kx': (i % 2 ? -1.2 : 1.2) + '%',
                               '--ky': (i % 3 ? -1.3 : 1.1) + '%' }}>
                  <span className="lpv-in">
                    {/* 28 Aug: the stage visual is now a LOOP generated from its own render, so the
                        fan actually turns and the beam actually lands. The still stays as the
                        poster, which is the frame the clip opens on, so there is never a gap
                        between the two. Only the active clip plays (see scenes/home.js). */}
                    {/* 14 Sep (Bazil: "should be a default image while loading"). The clip is 960px at a
                        low bitrate and three of the six open on an empty base that builds up, so while
                        it buffered the centre showed a soft, half-built scene that read as broken. The
                        default image is the clip's OWN finished frame (same framing, so the handover is
                        invisible), held on top until the clip reports it is actually playing, and put
                        back whenever it stalls. The old poster was a different render at 2:1. */}
                    <video src={`/assets/cycle3d/${s}-loop.mp4`} poster={`/assets/cycle3d/${s}-still.webp`}
                           muted loop playsInline preload={i === 0 ? 'auto' : 'none'}
                           tabIndex={-1} aria-hidden="true" />
                    <img className="lpv-still" src={`/assets/cycle3d/${s}-still.webp`} alt="" aria-hidden="true"
                         decoding="async" loading={i === 0 ? 'eager' : 'lazy'} />
                  </span>
                </span>
              ))}
            </div>
          </div>
        </div>

        <div className="lp-center" id="lpPanel" aria-live="polite">
          <div className="lp-ctx swap">
            {/* 28 Aug trim (client): no bullets, no meta row; the number rides BESIDE the
                title as one index row, and the link is just "Read more" + a drawn arrow. */}
            <div className="lp-trow">
                            {/* the number sits inside a MINIATURE of the ring, filled to the same fraction and
                  on the same easing, so the copy column reads as the other half of one instrument */}
              <span className="lp-cardno" aria-hidden="true">
                <span className="lp-dial" id="lpDial"><svg viewBox="0 0 40 40" aria-hidden="true"><circle className="dl-trk" cx="20" cy="20" r="19" pathLength="1" /><circle className="dl-arc" cx="20" cy="20" r="19" pathLength="1" /></svg><b id="lpNum">1</b></span><small>/ 6</small>
              </span>
              <h3 id="lpTitle">Engineering Design &amp; Consultation</h3>
            </div>
            <span className="lp-kick" id="lpKick">Where the facility is decided</span>
            <p id="lpDesc">Concept to detailed design across CSA and MEP.</p>
            <a className="lp-more" id="lpMore" href="/services/all#design"><span id="lpMoreT">See Engineering Design &amp; Consultation</span>
              <svg viewBox="0 0 26 10" fill="none" stroke="currentColor" strokeWidth="1.6"
                   strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <path d="M1 5h23" /><path d="M20 1.2 24 5l-4 3.8" />
              </svg>
            </a>
          </div>
        </div>
      </div>
    </section>


    {/* 28 Sep: the developer's Scroll to build 3D, the latest delivery, runs in the page itself (components/Build3D.jsx).
        It replaced DevBuild3D, which framed the previous delivery (public/3d) in an iframe. */}
    {/* 1 Oct ("hide first the 3d section on home page", then "unhide the 3d part"): SHOW_BUILD3D (top of this file) turns
        it off and on. While off, the section is not mounted and none of its 150 MB of models load. */}
    {SHOW_BUILD3D && <Build3D />}

    {/* Selected Work removed on client feedback (16:02) · KIV: returns with real
        project images once IAQ supplies them. The section lives in git history. */}

    {/* 10 Sep (client review, Nabilah): the news section at the foot of the homepage is replaced
        by the industry section, with visuals. The seven-market band moved here from above the
        facility build; the news rail came off the homepage and lives on /news. */}
    {/* 25 Sep (Bazil, circling the band: "put white spacing at the left and right and at the bottom"): the band is an
        inset panel now, white gutters either side (industry-grid.css .ig-grid) and white under it before the closing band */}
    <section className="sec" id="industries" style={{paddingTop:'clamp(48px,7vh,90px)',paddingBottom:'clamp(14px,2.2vh,28px)'}}>{/* 25 Sep, night (Bazil: "reduce bottom spacing"): the white under the market strip is a quarter of what it was */}
      <IndustryGrid />
    </section>

    {/* Careers section removed from the home page on client feedback (16:04);
        the Careers page itself is unchanged and stays in the nav. */}

    {/* 21 Sep: the home page's own copy of the closing band is gone; it renders the shared one
        (components/ClosingBand.jsx), rebuilt the same day with the ask leading. */}
    <ClosingBand note="Homepage concept · Brand Method" />
    </>
  )
}
