import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', protocolTimeout: 120000, args: ['--use-angle=metal', '--enable-gpu', '--no-sandbox'] })
const p = await b.newPage()
await p.setViewport({ width: 1440, height: 900, deviceScaleFactor: 1 })
await p.goto('http://localhost:5177/?noanim', { waitUntil: 'networkidle0', timeout: 60000 })
await new Promise(r => setTimeout(r, 2400))
const box = await p.evaluate(() => { const e = document.querySelector('.glance.gr'); const r = e.getBoundingClientRect(); return { top: r.top + scrollY, h: r.height } })
await p.evaluate(t => scrollTo(0, t), box.top - 40)
await new Promise(r => setTimeout(r, 1000))
await p.screenshot({ path: process.argv[2] + '/gr-a.png' })
await p.evaluate(t => scrollTo(0, t), box.top + box.h - 860)
await new Promise(r => setTimeout(r, 1000))
await p.screenshot({ path: process.argv[2] + '/gr-b.png' })
console.log(JSON.stringify(box))
await b.close()
