import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', protocolTimeout: 120000, args: ['--use-angle=metal', '--enable-gpu', '--no-sandbox'] })
const p = await b.newPage()
await p.setViewport({ width: 1440, height: 900, deviceScaleFactor: 1 })
await p.goto('http://localhost:52158/about?noanim', { waitUntil: 'networkidle0', timeout: 60000 })
await new Promise(r => setTimeout(r, 1800))
const mk = await p.$('.nav-has[data-hub="markets-hub"] > a')
await mk.hover(); await new Promise(r => setTimeout(r, 900))
const row = await p.$('.nav-has[data-hub="markets-hub"] .nm-rows > a:nth-child(2)')
await row.hover(); await new Promise(r => setTimeout(r, 700))
const info = await p.evaluate(() => { const h = document.querySelector('.nav-has[data-hub="markets-hub"]'); const m = h.querySelector('.nav-mega'); const r = m.getBoundingClientRect(); const rows=[...h.querySelectorAll('.nm-rows>a')]; return { open: m.className.includes('open'), rect: [r.left, r.top, r.width, r.height], marks: [...new Set(rows.map(a => getComputedStyle(a.querySelector('.nm-sq')).color))], lit: rows.filter(a=>a.classList.contains('lit')).map(a=>[getComputedStyle(a.querySelector('.nm-sq')).color, getComputedStyle(a.querySelector('em')).color]) } })
await p.screenshot({ path: process.argv[2] + '/markets-menu.png', clip: { x: 0, y: 0, width: 1440, height: Math.min(900, info.rect[1] + info.rect[3] + 30) } })
console.log(JSON.stringify(info))
// the Amendments tab, top of the list
await p.goto('http://localhost:52158/checklist.html', { waitUntil: 'networkidle0', timeout: 60000 })
await new Promise(r => setTimeout(r, 1200))
const ck = await p.evaluate(() => { const und=[...document.querySelectorAll('.stamp')].filter(s=>/undefined/.test(s.textContent)).length; const items=[...document.querySelectorAll('.item')]; const noTime=items.filter(i=>!i.querySelector('.stamp')).length; const noTag=items.filter(i=>!i.querySelector('.tags .t, .tags [class*="t-"]')).length; const first=items[0]; return { items: items.length, undefinedStamps: und, noTime, noTag, firstTags: first && first.querySelector('.tags') && first.querySelector('.tags').textContent.trim(), stampSample: [...document.querySelectorAll('.stamp')].slice(0,3).map(s=>s.textContent) } })
await p.screenshot({ path: process.argv[2] + '/checklist-top.png', clip: { x: 0, y: 0, width: 1440, height: 900 } })
await p.evaluate(() => scrollTo(0, 900)); await new Promise(r => setTimeout(r, 500))
await p.screenshot({ path: process.argv[2] + '/checklist-2.png', clip: { x: 0, y: 0, width: 1440, height: 900 } })
console.log(JSON.stringify(ck))
await b.close()
