import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', protocolTimeout: 120000, args: ['--use-angle=metal', '--enable-gpu', '--no-sandbox'] })
const p = await b.newPage()
await p.setViewport({ width: 1440, height: 900, deviceScaleFactor: 1 })
await p.goto('http://localhost:52158/about', { waitUntil: 'networkidle0', timeout: 60000 })
await new Promise(r => setTimeout(r, 2500))
const mk = await p.$('.nav-has[data-hub="markets-hub"] > a')
await mk.hover(); await new Promise(r => setTimeout(r, 1800))
const row = await p.$('.nav-has[data-hub="markets-hub"] .nm-rows > a:nth-child(2)')
await row.hover(); await new Promise(r => setTimeout(r, 1200))
const info = await p.evaluate(() => { const h = document.querySelector('.nav-has[data-hub="markets-hub"]'); const rows=[...h.querySelectorAll('.nm-rows>a')]; return rows.map(a => [a.textContent.trim().slice(0,20), getComputedStyle(a).opacity, getComputedStyle(a).transform, getComputedStyle(a.querySelector('.nm-sq')).color]) })
await p.screenshot({ path: process.argv[2] + '/markets-menu.png', clip: { x: 300, y: 60, width: 1000, height: 520 } })
console.log(JSON.stringify(info))
await b.close()
