import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--no-sandbox'] })
const p = await b.newPage()
await p.setViewport({ width: 1440, height: 900, deviceScaleFactor: 2 })
await p.goto('http://localhost:5177/?noanim&marks=line', { waitUntil: 'networkidle0', timeout: 60000 })
await new Promise(r => setTimeout(r, 2000))
await p.evaluate(() => document.querySelector('.hmk-row.hmk-iso').scrollIntoView({ block: 'center' }))
await new Promise(r => setTimeout(r, 600))
const a = await p.$$('.hmk-iso li a')
const before = await p.evaluate(el => ({ t: getComputedStyle(el.querySelector('svg')).transform, rule: getComputedStyle(el, '::after').width, c: getComputedStyle(el).color }), a[2])
const box = await a[2].boundingBox()
await p.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
await new Promise(r => setTimeout(r, 700))
const after = await p.evaluate(el => ({ t: getComputedStyle(el.querySelector('svg')).transform, rule: getComputedStyle(el, '::after').width, c: getComputedStyle(el).color }), a[2])
console.log(JSON.stringify({ before, after }, null, 1))
await (await p.$('.hmk')).screenshot({ path: process.argv[2] })
await b.close()
