import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', protocolTimeout: 120000, args: ['--no-sandbox', '--disable-gpu'] })
const p = await b.newPage()
const out = process.argv[2]; const wait = ms => new Promise(r => setTimeout(r, ms))
await p.setViewport({ width: 1440, height: 900, deviceScaleFactor: 1 })
await p.goto('http://localhost:52158/services', { waitUntil: 'networkidle0', timeout: 90000 }); await wait(2500)
/* the page has a sticky stage, so lower sections are shown by shifting the document, never by scrolling (hidden-pane rule) */
const shift = async (sel, name, off, h) => { const t = await p.evaluate(s => { document.documentElement.style.marginTop = ''; const e = document.querySelector(s); return e ? e.getBoundingClientRect().top + scrollY : null }, sel); if (t == null) { console.log('missing', sel); return } await p.evaluate(y => { document.documentElement.style.marginTop = (-y) + 'px' }, t - off); await wait(2200); await p.screenshot({ path: `${out}/${name}.png`, clip: { x: 0, y: 0, width: 1440, height: h } }) }
await shift('.sm-asks', 'svc-asks', 70, 700)
const asks = await p.evaluate(() => ({ unitMarks: document.querySelectorAll('.sm-chip.u svg.sm-ci').length, modelMarks: document.querySelectorAll('.sm-chip.m svg.sm-ci').length, stageMarks: document.querySelectorAll('.sm-chip.s .sm-cm svg').length, workMarks: document.querySelectorAll('.sm-chip.w svg.sm-ci').length, sysMarks: document.querySelectorAll('.sm-chip.y svg.sm-ci').length, markBox: document.querySelector('.sm-chip.u svg.sm-ci').getBoundingClientRect().width }))
await shift('.sysm', 'svc-chart', 30, 820)
const chart = await p.evaluate(() => { const cells = [...document.querySelectorAll('.sysm-bar i')]; return { named: cells.filter(c => c.textContent.trim()).length, clipped: cells.filter(c => c.scrollWidth > c.clientWidth + 1).length } })
await shift('.sm-map-dark.sm-map-full', 'svc-band-foot', -0, 900)
await p.evaluate(() => { document.documentElement.style.marginTop = '' })
const band = await p.evaluate(() => { const s = document.querySelector('.sm-map-dark.sm-map-full'); const r = s.getBoundingClientRect(); document.documentElement.style.marginTop = (-(r.bottom + scrollY) + 640) + 'px'; return getComputedStyle(s).paddingBottom })
await wait(1500); await p.screenshot({ path: `${out}/svc-band-foot.png`, clip: { x: 0, y: 0, width: 1440, height: 800 } })
console.log(JSON.stringify({ asks, chart, band }))
await p.setViewport({ width: 390, height: 844, deviceScaleFactor: 1 })
await p.goto('http://localhost:52158/services', { waitUntil: 'networkidle0', timeout: 90000 }); await wait(2500)
const ph = await p.evaluate(() => ({ docW: document.documentElement.scrollWidth, cellsClipped: [...document.querySelectorAll('.sysm-bar i')].filter(c => c.scrollWidth > c.clientWidth + 1).length, cellText: [...document.querySelectorAll('.sysm-bar')][0] && getComputedStyle(document.querySelector('.sysm-bar i.core span'), '::before').content }))
const t = await p.evaluate(() => { const e = document.querySelector('.sysm'); return e.getBoundingClientRect().top + scrollY })
await p.evaluate(y => { document.documentElement.style.marginTop = (-y + 10) + 'px' }, t); await wait(2200)
await p.screenshot({ path: `${out}/svc-chart-390.png`, clip: { x: 0, y: 0, width: 390, height: 844 } })
console.log('phone', JSON.stringify(ph))
await b.close()
