/* Summarise the crawler report into the findings the QA page needs. Usage: node tools/audit-summary.mjs <auditDir> */
import fs from 'node:fs'
const dir = process.argv[2]; const { report, discovered } = JSON.parse(fs.readFileSync(dir + '/report.json', 'utf8'))
const desk = report.filter(r => r.vp === 'desktop'), mob = report.filter(r => r.vp === 'mobile')
const row = r => [r.route, r.title?.replace('IAQ Group · ', '').replace(' · Brand Method', ''), r.h1.length, r.skips, r.imgs, r.imgNoAlt, r.imgBroken.length, r.emptyLinks, r.nameless, Object.values(r.ph).reduce((a, b) => a + b, 0), r.dashes, r.words, r.longSentences, r.height, r.sections, Math.round(r.bytes / 1024), r.requests, r.load, r.errs.length, r.bad.length + r.failed.length, r.metaDesc ? 'y' : 'n', r.ctas]
console.log('route | title | h1 | skips | imgs | noAlt | broken | emptyLinks | nameless | placeholders | dashes | words | longSent | height | sections | KB | reqs | load ms | errs | badReq | meta | ctas')
for (const r of desk) console.log(row(r).join(' | '))
console.log('\n=== MOBILE: overflow / small text / height ===')
for (const r of mob) if (r.overflowX || r.small > 0) console.log(r.route, 'overflowX', r.overflowX, 'scrollWidth', r.scrollWidth, 'small<11px', r.small, 'height', r.height)
console.log('\n=== console errors (unique, all captures) ===')
const errs = new Map(); for (const r of report) for (const e of r.errs) errs.set(e, (errs.get(e) || []).concat(r.route + '@' + r.vp))
for (const [e, rs] of errs) console.log('-', e.slice(0, 200), '\n   on', [...new Set(rs)].slice(0, 6).join(', '))
console.log('\n=== bad / failed requests (unique) ===')
const bad = new Map(); for (const r of report) for (const e of [...r.bad, ...r.failed]) bad.set(e, (bad.get(e) || []).concat(r.route))
for (const [e, rs] of bad) console.log('-', e, '  on', [...new Set(rs)].slice(0, 5).join(', '))
console.log('\n=== broken images (unique) ===')
const bi = new Map(); for (const r of report) for (const e of r.imgBroken) bi.set(e, (bi.get(e) || []).concat(r.route))
for (const [e, rs] of bi) console.log('-', e, '  on', [...new Set(rs)].slice(0, 5).join(', '))
console.log('\n=== internal links pointing at no route ===')
const routes = new Set(['/', '/about', '/about/history', '/about/commitment', '/about/leadership', '/about/esg', '/global-presence', '/services', '/services/design', '/services/procurement', '/services/construction', '/services/commissioning', '/services/maintenance', '/services/epc-construction', '/services/process-critical-utilities', '/services/tool-installation', '/services/energy-management', '/markets', '/markets/semiconductor', '/markets/data-centre', '/markets/ev-battery', '/markets/photovoltaics', '/markets/district-cooling', '/markets/bio-lifescience', '/markets/food-beverage', '/projects', '/news', '/careers', '/contact', '/investors', '/policies', '/exhibition', '/shortlist', '/portal', '/flow', '/fab', '/home2', '/about2'])
const badLinks = new Map()
for (const r of desk) for (const l of r.internal) { const p = l.split('#')[0]; if (!routes.has(p) && !/^\/(projects|news|lp)\/[^/]+$/.test(p)) badLinks.set(l, (badLinks.get(l) || []).concat(r.route)) }
for (const [l, rs] of badLinks) console.log('-', l, '  from', [...new Set(rs)].slice(0, 6).join(', '))
console.log('\n=== external links ==='); const ext = new Set(); for (const r of desk) for (const l of r.external) ext.add(l); console.log([...ext].join('\n'))
console.log('\n=== placeholders by phrase (desktop) ==='); const ph = {}; for (const r of desk) for (const [k, v] of Object.entries(r.ph)) ph[k] = (ph[k] || 0) + v; console.log(ph)
console.log('\n=== titles duplicated ==='); const t = {}; for (const r of desk) t[r.title] = (t[r.title] || []).concat(r.route); for (const [k, v] of Object.entries(t)) if (v.length > 1) console.log('-', k, '→', v.join(', '))
console.log('\n=== heading lists for pages with skips or no h1 ==='); for (const r of desk) if (r.skips || r.h1.length !== 1) console.log(r.route, 'h1:', JSON.stringify(r.h1), 'skips', r.skips, '\n   ', r.headingList.map(h => 'h' + h.l + ' ' + h.t).slice(0, 14).join(' | '))
console.log('\n=== weight ==='); const tot = desk.reduce((a, r) => a + r.bytes, 0); console.log('avg KB per page', Math.round(tot / desk.length / 1024), '· heaviest:', desk.sort((a, b) => b.bytes - a.bytes).slice(0, 5).map(r => r.route + ' ' + Math.round(r.bytes / 1024) + 'KB').join(', '))
console.log('discovered dynamic:', discovered.join(' '))
