/* export-icons.mjs · 25 Sep 2026. Reads the live icon library on /portal/direction and writes a static copy of every
   icon (each element's computed stroke, fill and weights inlined, animations stopped on the finished drawing) into
   public/design.html between the ICON-LIBRARY markers. Run with the dev server up:
   NODE_PATH=<puppeteer> node tools/export-icons.mjs */
import puppeteer from 'puppeteer-core'
import fs from 'node:fs'
const BASE = process.argv[2] || 'http://localhost:5177'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new' })
const p = await b.newPage(); await p.setViewport({ width: 1440, height: 900 })
await p.goto(BASE + '/portal', { waitUntil: 'load' }); await p.evaluate(() => localStorage.setItem('iaq.cms.session.v1', '1'))
await p.goto(BASE + '/portal/direction?source', { waitUntil: 'load' }); await new Promise(r => setTimeout(r, 4000))   /* ?source: the React page; without it the portal shows the Design tab itself */
await p.addStyleTag({ content: '#icon-library *{animation:none!important;transition:none!important}' })
await new Promise(r => setTimeout(r, 600))
const groups = await p.evaluate(() => {
  const PROPS = ['stroke', 'fill', 'stroke-width', 'opacity', 'fill-opacity', 'stroke-opacity', 'stroke-dasharray', 'stroke-linecap', 'stroke-linejoin', 'display', 'transform', 'font-size', 'font-weight', 'letter-spacing', 'font-family']
  const snap = svg => {
    const c = svg.cloneNode(true)
    const src = [svg, ...svg.querySelectorAll('*')], dst = [c, ...c.querySelectorAll('*')]
    src.forEach((el, i) => {
      const cs = getComputedStyle(el), st = []
      for (const k of PROPS) { const v = cs.getPropertyValue(k); if (v && v !== 'none' || k === 'fill' || k === 'stroke' || k === 'display') { if (k === 'transform' && v === 'none') continue; st.push(k + ':' + v) } }
      dst[i].setAttribute('style', st.join(';')); dst[i].removeAttribute('class')
    })
    c.setAttribute('width', Math.round(svg.getBoundingClientRect().width)); c.setAttribute('height', Math.round(svg.getBoundingClientRect().height))
    c.querySelectorAll('title').forEach(t => t.remove())
    return c.outerHTML
  }
  return [...document.querySelectorAll('#icon-library .il-g')].map(g => ({
    name: g.querySelector('h3').childNodes[1].textContent, dark: g.classList.contains('il-dark'), lg: !!g.querySelector('.il-grid-lg'),
    dot: getComputedStyle(g.querySelector('h3 i')).backgroundColor,
    items: [...g.querySelectorAll('.il-it')].map(f => { const sv = f.querySelector('svg'), media = f.querySelector('.il-obj3'); return { l: f.querySelector('figcaption').textContent, svg: sv ? snap(sv) : media ? media.outerHTML.replace(/<video /g, '<video muted ').replace(/ autoplay=""/g, ' autoplay') : '' } }),
  }))
})
await b.close()
const esc = t => t.replace(/&/g, '&amp;').replace(/</g, '&lt;')
const html = `<!-- ICON-LIBRARY:START (generated by tools/export-icons.mjs from /portal/direction, ${new Date().toISOString().slice(0, 10)}) -->
    <h3 style="margin-top:44px;font-size:17px" id="icon-library">The icon library, as the site draws it today</h3>
    <p class="note">Every icon set from the live components, in the kind colours: services red, units in three blues, work black,
      systems green, markets violet with white on navy, delivery models and interface marks ink. Never in a box. The live,
      animated version is on the portal&rsquo;s Design direction page; this copy is regenerated by <code>tools/export-icons.mjs</code>.</p>
    <style>.ilx-g{margin-top:26px}.ilx-g h4{display:flex;align-items:center;gap:10px;margin:0 0 14px;font:600 15px/1.2 "Switzer",sans-serif}.ilx-g h4 i{width:10px;height:10px;display:block}.ilx-g h4 small{font:500 12px/1 "Instrument Sans",sans-serif;opacity:.55}.ilx-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(118px,1fr));gap:20px 14px}.ilx-lg .ilx-grid{grid-template-columns:repeat(auto-fill,minmax(170px,1fr))}.ilx-it{margin:0;display:grid;justify-items:center;gap:10px;text-align:center}.ilx-it figcaption{font:500 12px/1.3 "Instrument Sans",sans-serif;opacity:.7}.ilx-dark{background:#17213A;color:#fff;padding:20px 20px 24px}.ilx-it svg{overflow:visible}</style>
${groups.map(g => `    <div class="ilx-g${g.dark ? ' ilx-dark' : ''}${g.lg ? ' ilx-lg' : ''}">
      <h4><i style="background:${g.dot}"></i>${esc(g.name)}<small>${g.items.length}</small></h4>
      <div class="ilx-grid">
${g.items.map(it => `        <figure class="ilx-it">${it.svg}<figcaption>${esc(it.l)}</figcaption></figure>`).join('\n')}
      </div>
    </div>`).join('\n')}
<!-- ICON-LIBRARY:END -->`
const f = 'public/design.html'
let s = fs.readFileSync(f, 'utf8')
if (s.includes('<!-- ICON-LIBRARY:START')) s = s.replace(/<!-- ICON-LIBRARY:START[\s\S]*?<!-- ICON-LIBRARY:END -->/, html)
else {
  const anchor = '<h3 style="margin-top:44px;font-size:17px" id="iso-family">'
  if (!s.includes(anchor)) throw new Error('anchor missing')
  s = s.replace(anchor, html + '\n\n    ' + anchor)
}
fs.writeFileSync(f, s)
console.log('icons exported:', groups.map(g => g.name + ' ' + g.items.length).join(', '), '| bytes', html.length)
